# Test Senario Ver.0.1
# 

[meta]
name = "test_senario1"
falling_speed = 1.0

[[Senarios]]
senario_name = "Trainning1"
type = "train"
digits = 4
[[Senarios.spawn_delay_times]]
spawn_delay_time = 10.0
change_at = 0.0
[[Senarios.spawn_delay_times]]
spawn_delay_time = 10.0
change_at = 30.0
[[Senarios.spawn_delay_times]]
spawn_delay_time = 8.0
change_at = 90.0
[[Senarios.spawn_delay_times]]
spawn_delay_time = 8.0
change_at = 240.0

[[Senarios]]
senario_name = "Trainning2"
type = "train"
digits = 4
[[Senarios.spawn_delay_times]]
spawn_delay_time = 10.0
change_at = 0.0
[[Senarios.spawn_delay_times]]
spawn_delay_time = 10.0
change_at = 30.0
[[Senarios.spawn_delay_times]]
spawn_delay_time = 6.0
change_at = 90.0
[[Senarios.spawn_delay_times]]
spawn_delay_time = 8.0
change_at = 240.0

[[Senarios]]
senario_name = "Trainning3"
type = "train"
digits = 4
[[Senarios.spawn_delay_times]]
spawn_delay_time = 10.0
change_at = 0.0
[[Senarios.spawn_delay_times]]
spawn_delay_time = 4.0
change_at = 90.0
[[Senarios.spawn_delay_times]]
spawn_delay_time = 4.0
change_at = 240.0


[[Senarios]]
senario_name = "Trainning4"
type = "train"
digits = 4
[[Senarios.spawn_delay_times]]
spawn_delay_time = 10.0
change_at = 0.0
[[Senarios.spawn_delay_times]]
spawn_delay_time = 5.0
change_at = 90.0
[[Senarios.spawn_delay_times]]
spawn_delay_time = 1.0
change_at = 300.0
