# Test Senario Ver.0.1
# 

[meta]
name = "test_senario"
falling_speed = 0.3

[[Senarios]]
senario_name = "Trainning1"
type = "train"
[[Senarios.spawn_delay_times]]
spawn_delay_time = 4.0
change_at = 0.0
[[Senarios.spawn_delay_times]]
spawn_delay_time = 4.0
change_at = 5.0
[[Senarios.spawn_delay_times]]
spawn_delay_time = 2.0
change_at = 10.0


[[Senarios]]
senario_name = "Trainning2"
type = "train"
[[Senarios.spawn_delay_times]]
spawn_delay_time = 4.0
change_at = 0.0
[[Senarios.spawn_delay_times]]
spawn_delay_time = 10.0
change_at = 5.0
[[Senarios.spawn_delay_times]]
spawn_delay_time = 8.0
change_at = 10.0
