# Test Senario Ver.0.4
# Last Change at Dec.20
# ! 本実験 ver.

[meta]
name = "test_senario3"
falling_speed = 0.75

# １．練習タスク
[[Senarios]]
senario_name = "Practice1"
type = "train"
digits = 4
life = 3
number_of_delete_on_decrease_life = 0
range_of_delete_on_decrease_life = 6.0
[[Senarios.spawn_delay_times]]
spawn_delay_time = 5.0
change_at = 0.0
[[Senarios.spawn_delay_times]]
spawn_delay_time = 5.0
change_at = 30.0
[[Senarios.spawn_delay_times]] 
spawn_delay_time = 4.0
change_at = 180.0

# 2. 測定（遅め）
[[Senarios]]
senario_name = "GetPerformance_max2"
type = "measure"
digits = 4
life = 3
number_of_delete_on_decrease_life = 0
range_of_delete_on_decrease_life = 6.0
[[Senarios.spawn_delay_times]]
spawn_delay_time = 3.5
change_at = 0.0
[[Senarios.spawn_delay_times]]
spawn_delay_time = 2.3
change_at = 90.0
[[Senarios.spawn_delay_times]]
spawn_delay_time = 1.5
change_at = 300.0

# 3. 測定（はやめ）
[[Senarios]]
senario_name = "GetPerformance_high_max3"
type = "measure"
digits = 4
life = 3
number_of_delete_on_decrease_life = 0
range_of_delete_on_decrease_life = 6.0
[[Senarios.spawn_delay_times]]
spawn_delay_time = 3.0
change_at = 0.0
[[Senarios.spawn_delay_times]]
spawn_delay_time = 2.0
change_at = 90.0
[[Senarios.spawn_delay_times]]
spawn_delay_time = 1.3
change_at = 300.0

# 4. １桁の低条件
[[Senarios]]
senario_name = "TP_nothing4"
type = "auto"
digits = 1
life = 3
number_of_delete_on_decrease_life = 0
range_of_delete_on_decrease_life = 6.0
[[Senarios.spawn_delay_times]]
spawn_delay_time = 1.5
change_at = 0.0
[[Senarios.spawn_delay_times]]
spawn_delay_time = 1.14
change_at = 60.0
[[Senarios.spawn_delay_times]]
spawn_delay_time = 1.14
change_at = 300.0

# 5. ４桁の低条件
[[Senarios]]
senario_name = "TP_low5"
type = "auto"
digits = 4
life = 3
number_of_delete_on_decrease_life = 0
range_of_delete_on_decrease_life = 6.0
[[Senarios.spawn_delay_times]]
spawn_delay_time = 1.5
change_at = 0.0
[[Senarios.spawn_delay_times]]
spawn_delay_time = 1.14
change_at = 60.0
[[Senarios.spawn_delay_times]]
spawn_delay_time = 1.14
change_at = 300.0

# 6. ４桁の高条件
[[Senarios]]
senario_name = "TP_high6"
type = "auto"
digits = 4
life = 3
number_of_delete_on_decrease_life = 0
range_of_delete_on_decrease_life = 6.0
[[Senarios.spawn_delay_times]]
spawn_delay_time = 1.5
change_at = 0.0
[[Senarios.spawn_delay_times]]
spawn_delay_time = 0.89
change_at = 60.0
[[Senarios.spawn_delay_times]]
spawn_delay_time = 0.89
change_at = 300.0